crowdfunding/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import home
urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('newproj/', include('newproj.urls')),
    path('homepage/', include('homepage.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newproj/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects_list, name='projects_list'),
    path('create/', views.create_project, name='create_project'),
    path('<slug:slug>/', views.project_details, name='project_details'),
    path('<slug:slug>/rate', views.rate_project, name='rate_project'),
    path('<slug:slug>/donate/', views.add_donation, name='add_donation'),
    path('<slug:slug>/cancel/', views.cancel_project, name='cancel_project'),
    path('<slug:slug>/rate/', views.rate_project, name='rate_project'),
    path('<slug:slug>/donate/', views.add_donation, name='add_donation'),
    path('<slug:slug>/comment/', views.add_comment, name='add_comment'),
    path('<slug:slug>/report/', views.report_project, name='report_project'),
    path('comments/<int:comment_id>/report/', views.report_comment, name='report_comment'),
    path('tags/<slug:slug>/', views.tagged, name="tagged"),
]

newproj/models.py
import os

from django.utils import timezone
from django.utils.text import slugify
from django.db import models
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.core.validators import MaxValueValidator, MinValueValidator
from taggit.managers import TaggableManager
from accounts.models import CustomUser
# from apps.categories.models import Category

#======================= categories model ====================
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# ===================== Project Model =====================
class Project(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, editable=False, blank=True)
    details = models.TextField()
    total_target = models.IntegerField()
    current_fund = models.IntegerField(default=0)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    # category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=None, related_name='projects')
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField()
    tags = TaggableManager()
    updated_at = models.DateTimeField(auto_now=True)
    rate = models.FloatField(default=0, null=True, validators=[MinValueValidator(0.5), MaxValueValidator(5.0)])
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    featured = models.BooleanField(default=False)
    featured_at = models.DateTimeField(default=None, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        # Check if current_fund has reached total_target and update status to 'completed'
        if self.current_fund >= self.total_target and self.status != 'completed':
            self.status = 'completed'

        # Check if featured field has changed and update featured_at
        if self.featured and not self.featured_at:
            self.featured_at = timezone.now()
        elif not self.featured:
            self.featured_at = None

        super(Project, self).save(*args, **kwargs)

    @classmethod
    def get_project_by_slug(cls, slug):
        return get_object_or_404(cls, slug=slug)

    @property
    def show_url(self):
        return reverse('project_details', args=[self.slug])

    @property
    def update_url(self):
        return reverse('update_project', args=[self.slug])

    @property
    def cancel_url(self):
        return reverse('cancel_project', args=[self.slug])

    @property
    def pictures_urls(self):
        return [pic.image.url for pic in self.pictures.all()]

    @property
    def picture_url(self):
        first_picture = self.pictures.first()
        if first_picture:
            return first_picture.image.url

    @property
    def get_tags(self):
        return self.tags.all()

    @property
    def percentag(self):
        if self.total_target == 0:
            return 0
        value = (self.current_fund * 100) / self.total_target
        return round(value, 2)


# ===================== ProjectPicture Model =====================
def project_picture_upload_path(instance, filename):
    if instance.project.pictures.exists():
        project_directory_name = os.path.dirname(instance.project.pictures.first().image.path)
    else:
        project_directory_name = instance.project.title.replace(' ', '_')
    return os.path.join('project_uploads', project_directory_name, filename)


class ProjectPicture(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="pictures")
    image = models.ImageField(db_column='image', upload_to=project_picture_upload_path)

    @property
    def image_url(self):
        return f"/media/{self.image}"


# ===================== Donation Model =====================
class Donation(models.Model):
    amount = models.IntegerField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='donations')
    user = models.ForeignKey(CustomUser, on_delete=models.SET_DEFAULT, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.amount


# ===================== Comment Model =====================
class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,default=None, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


# ===================== Reply Model =====================
class Reply(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE ,default=None, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class CommentReport(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


# ===================== Report Project Model =====================
class ProjectReport(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


# ===================== Rating Model =====================
class Rating(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='ratings')
    value = models.FloatField(validators=[MinValueValidator(0.5), MaxValueValidator(5.0)])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'project')

newproj/views.py
import os
import re
import shutil

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Max
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from taggit.models import Tag

from .forms import ProjectForm, DonationForm, CommentForm, ReportProjectForm, ReportCommentForm
from .models import Project, ProjectPicture, Donation, Comment, Rating
from accounts.models import CustomUser


@login_required(login_url='login_')
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            user_instance = CustomUser.objects.get(pk=request.user.pk)
            project_pictures = request.FILES.getlist('pictures')
            tags = form.cleaned_data.get('tags', [])

            if len(project_pictures) == 0:
                messages.error(request, f'You should choose at least 1 picture.')
                return render(request, 'newproj/creat_proj.html', {'form': form})

            if len(tags) > 5:
                form.add_error('tags', "Maximum 5 tags allowed.")
            for tag in tags:
                if not re.match(r'^[a-zA-Z0-9_]+$', tag):
                    form.add_error('tags', "Tags can only contain letters, numbers, and underscore.")
                    break
            if form.errors:
                return render(request, 'newproj/creat_proj.html', {'form': form})

            project = form.save(commit=False)
            project.creator = user_instance
            project.save()
            form.save_m2m()

            for pic in project_pictures:
                ProjectPicture.objects.create(project=project, image=pic)

            return redirect('project_details', slug=project.slug)
    else:
        form = ProjectForm()
    return render(request, 'newproj/creat_proj.html', {'form': form})


@login_required(login_url='login_')
def rate_project(request, slug):
    if request.method == 'POST':
        project = get_object_or_404(Project, slug=slug)
        print(project, "rate")
        rating_value = float(request.POST.get('rating'))
        print(rating_value, "rate")
        current_user = CustomUser.objects.get(pk=request.user.pk)
        # if current_user.is_authenticated:
        # Check if the user has already rated the project
        existing_rating = Rating.objects.filter(user=current_user, project=project).first()
        if existing_rating:
            # Update existing rating
            existing_rating.value = rating_value
            existing_rating.save()
            messages.success(request, 'Your rating has been updated.')
        else:
            # Create a new rating object
            Rating.objects.create(user=current_user, project=project, value=rating_value)
            messages.success(request, 'Thank you for rating this project.')
        return JsonResponse({
            'success': True,
            'project_title': project.title,
            'project_slug': project.slug,
            'rating_value': rating_value,
        })
        # else:
        #     return JsonResponse({'success': False, 'error': 'Authentication required'}, status=401)
    else:
        # Return a JSON response indicating failure
        return JsonResponse({'success': False, 'error': 'Method not allowed'}, status=405)


def project_details(request, slug):
    project = get_object_or_404(Project, slug=slug)
    comments = project.comments.all()
    comments = Comment.objects.filter(project=project)
    # for comment in comments:
    #     comment.replies = Reply.objects.filter(comment=comment)
    # Calculate days left until end time

    end_datetime = project.end_time
    now_datetime = timezone.now()
    days_left = (end_datetime.date() - now_datetime.date()).days

    average_rating = project.ratings.aggregate(Avg('value'))['value__avg']
    print(average_rating, "avg")
    if average_rating is not None:
        project.rate = round(average_rating, 2)
        print(project.rate, "pro")
    else:
        project.rate = None

    project.save()

    user_rating = None
    if request.user.is_authenticated:
        current_user = request.user
        user_rating_obj = Rating.objects.filter(user=current_user, project=project).first()
        if user_rating_obj:
            user_rating = user_rating_obj.value

    related_projects = Project.objects.filter(tags__in=project.tags.all()).exclude(id=project.id).distinct()[:4]
    for related_project in related_projects:
        end_datetime = related_project.end_time
        now_datetime = timezone.now()
        days_left = (end_datetime.date() - now_datetime.date()).days
        related_project.days_left = days_left

    first_donation = Donation.objects.filter(project=project).order_by('created_at').first()
    last_donation = Donation.objects.filter(project=project).order_by('-created_at').first()
    top_donation = Donation.objects.filter(project=project).aggregate(Max('amount'))['amount__max']
    top_donation_user = CustomUser.objects.filter(
        donation__amount=Donation.objects.aggregate(max_amount=Max('amount'))['max_amount']).first()

    # if project.total_target != 0:
    #     current_fund_percentage = round((project.current_fund / project.total_target) * 100, 2)
    # else:
    #     current_fund_percentage = 0  # Handle division by zero case

    num_donors = Donation.objects.filter(project=project).values('user').distinct().count()

    allow_cancel = False
    if request.user.id == project.creator.id and project.percentag < 25:
        allow_cancel = True

    context = {
        'project': project,
        'comments': comments,
        'days_left': days_left,
        'user_rating': user_rating,
        'average_rating': average_rating,
        'related_projects': related_projects,
        'first_donation': first_donation,
        'last_donation': last_donation,
        'top_donation': top_donation,
        'top_donation_user': top_donation_user,
        'num_donors': num_donors,
        # 'current_fund_percentage': current_fund_percentage,
        'allow_cancel': allow_cancel,
    }
    return render(request, 'newproj/project_details.html', context)


def projects_list(request):
    projects = Project.objects.all().filter(status='active')
    return render(request, 'newproj/index.html', {'projects': projects})


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    projects = Project.objects.filter(tags=tag, status='active')
    return render(request, 'newproj/tagged.html', {'tag': tag, 'projects': projects})


@login_required(login_url='login_')
def cancel_project(request, slug):
    project = Project.get_project_by_slug(slug)
    project_directory = os.path.join(settings.MEDIA_ROOT, 'project_uploads', project.title.replace(' ', '_'))

    current_fund = project.current_fund
    recipient_project = Project.objects.filter(category=project.category).exclude(pk=project.pk).first()

    # add the current fund of that project to another project in the same category
    if recipient_project:
        recipient_project.current_fund += current_fund
        recipient_project.save()

    else:
        # If no project in the same category, transfer the funds to any available project
        recipient_project = Project.objects.exclude(pk=project.pk).first()
        recipient_project.current_fund += current_fund
        recipient_project.save()

    # Delete the project directory
    if os.path.exists(project_directory):
        shutil.rmtree(project_directory)

    project.delete()
    return redirect('/')


@login_required(login_url='login_')
def add_donation(request, slug):
    project = get_object_or_404(Project, slug=slug)
    if request.method == 'POST':
        donation_form = DonationForm(request.POST)
        if donation_form.is_valid():
            donation = donation_form.save(commit=False)
            donation.project = project
            user_instance = CustomUser.objects.get(pk=request.user.pk)
            donation.user = user_instance
            project.current_fund += donation.amount
            if project.current_fund > project.total_target:
                messages.error(request, 'please enter a donation amount lower than the total target')
                return render(request, 'newproj/project_details.html', {'project': project})
            donation.save()
            project.save()
            messages.success(request, 'Thank you for your donation!')
            return redirect('project_details', slug=slug)
    else:
        donation_form = DonationForm()
    return render(request, 'newproj/project_details.html', {'donation_form': donation_form, 'project': project})


@login_required(login_url='login_')
def add_comment(request, slug):
    project = get_object_or_404(Project, slug=slug)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.project = project
            user_instance = CustomUser.objects.get(pk=request.user.pk)
            comment.user = user_instance
            comment.save()
            messages.success(request, 'Your comment has been added!')
            return redirect('project_details', slug=slug)
    else:
        comment_form = CommentForm()
    return render(request, 'newproj/add_comment.html', {'comment_form': comment_form, 'project': project})

@login_required(login_url='login_')
def report_project(request, slug):
    project = Project.get_project_by_slug(slug)
    if request.method == 'POST':
        report_project_form = ReportProjectForm(request.POST)
        if report_project_form.is_valid():
            report = report_project_form.save(commit=False)
            report.project = project
            user_instance = CustomUser.objects.get(pk=request.user.pk)

newproj/templates/newproj/add_comment.html
 <!-- Add Comment Form Modal -->
 <div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="commentModalLabel">Add Comment to {{ project.title }}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form action="{% url 'add_comment' project.slug %}" method="post">
                      {% csrf_token %}
                      <textarea name="text" class="form-control" rows="3"
                          placeholder="Write your comment here" required></textarea>
                      <button type="submit" class="btn btn-primary">Add Comment</button>
                  </form>
              </div>
          </div>
      </div>
  </div>

newproj/templates/newproj/cancel_project.html
<a class="btn btn-danger border delete-book" data-bs-target="#deleteModal{{ project.id }}" data-bs-toggle="modal">Cancel
    project</a>

<!-- Start Delete Modal -->
<div aria-hidden="true" aria-labelledby="deleteModalLabel" class="modal fade" id="deleteModal{{ project.id }}"
    role="dialog" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm project cancellation</h5>
                <button aria-label="Close" class="close" data-bs-dismiss="modal" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to cancel "{{ project }}"?
            </div>
            <div class="modal-footer">
                <form action="{{ project.cancel_url }}" id="delete-project-form-{{ project.id }}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Yes</button>
                    <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">No</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Delete Modal -->

newproj/templates/newproj/creat_proj.html
{% extends "base.html" %}

{% load static %}

{% block title %} Create new project {% endblock %}

{% block styles %}

<link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">

<link href="/static/projects/css/tagsinput.css" rel="stylesheet"/>

<style>
    .glass {
        background: linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0));
        backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.18);
        -webkit-backdrop-filter: blur(10px);
        border-radius: 20px;
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37)
    }
</style>

{% endblock %}

{% block navbar %}



{% endblock%}

{% block content %}

<section>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8 col-lg-8 mx-md-auto">
                    <form action="." class="p-3 m-5 rounded glass" enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        <h1 class="my-3">Create new project</h1>

                        <!-- Start title -->
                        <div class="mb-3">
                            <label class="form-label" for="id_title">Title</label>
                            <div class="input-group has-validation">
                                {{ form.title }}
                            </div>
                            {% for error in form.title.errors %}
                            <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <!-- End title -->

                        <!-- Start details -->
                        <div class="mb-4">
                            <label class="form-label" for="id_details">Details</label>
                            <div class="input-group has-validation">
                                {{ form.details }}
                            </div>
                            {% for error in form.details.errors %}
                            <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <!-- End details -->

                        <div class="row">
                            <!-- Start start_time -->
                            <div class="mb-4 col-md-6">
                                <label class="form-label" for="id_start_time">Start Time</label>
                                <div class="input-group has-validation">
                                    {{ form.start_time }}
                                </div>
                                {% for error in form.start_time.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <!-- End start_time -->

                            <!-- start end_time -->
                            <div class="mb-4 col-md-6">
                                <label class="form-label" for="id_end_time">End Time</label>
                                <div class="input-group has-validation">
                                    {{ form.end_time }}
                                </div>
                                {% for error in form.end_time.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <!-- End end_time -->
                        </div>

                        <div class="row">
                            <!-- Start total_target -->
                            <div class="mb-4 col-md-6">
                                <label class="form-label" for="id_total_target">Total Target</label>
                                <div class="input-group has-validation">
                                    {{ form.total_target }}
                                </div>
                                {% for error in form.total_target.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <!-- End total_target -->

                            <!-- Start category -->
                            <div class="mb-4 col-md-6">
                                <label class="form-label" for="id_category">Category</label>
                                <div class="input-group has-validation">
                                    <select class="form-select" id="id_category" name="category">
                                        <option disabled selected value="">Select category</option>
                                        {% for op in form.category.field.choices %}
                                            {% if op.1 != '---------' %}
                                                <option value="{{ op.0 }}">{{ op.1 }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                                {% for error in form.category.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <!-- End category -->
                        </div>

                        <!-- Start pictures -->
                        <div class="form-group mb-4">
                            <label class="form-label" for="id_pictures">Pictures</label>
                            <input accept="image/jpeg, image/png, image/jpg" class="form-control" id="id_pictures" multiple name="pictures" type="file">
                            {% if messages %}
                                {% for message in messages %}
                                <p class="text-danger mt-1">{{ message }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <!-- End pictures -->

                        <!-- Start tags -->
                        <div class="form-group mb-4">
                            <label class="form-label" for="id_tags">Tags</label>
                            <input data-role="tagsinput" id="id_tags" name="tags" type="text">
                            {% for error in form.tags.errors %}
                                <div class="invalid-feedback d-block">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <!-- End tags -->

                        <div class="text-center my-3">
                            <button class="btn btn-primary" type="submit">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script crossorigin="anonymous"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

<script crossorigin="anonymous"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<script crossorigin="anonymous"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<script src="{% static 'projects/js/tagsinput.js' %}"></script>

<script src="{% static 'projects/js/script.js' %}"></script>

{% endblock %}

newproj/templates/newproj/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if projects %}
    <ul>
        {% for project in projects %}
        <li>{{ project }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

newproj/templates/newproj/tagged.html
{% extends "base.html" %}
{% load static %}

{% block title %} Tag | {{ tag }} {% endblock %}

{% block navbar %}

{% endblock %}
{% block styles %}

<style>
    .margine {
        margin-top: 90px;
    }

    .btnsign {
        color: aliceblue;
        background-color: #012555;
        border-color: #012555;
    }

    .btnsign:hover {
        color: aliceblue;
        background-color: #3dd0d8;
        border-color: #3dd0d8;
    }

</style>
{% endblock %}
{% block content %}
<div class="container margine">
    <div class="row mb-2">
        <h3 class="text-center mb-4 text-secondary  text-capitalize ">projects with tag ({{tag}})</h3>
        {% for project in projects %}
        <div class="item col-3">
            <div class="card p-2 bg-light">
                <img alt="project" class="card-img-top" src="{{project.picture_url}}"
                     style=" height: 200px; width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">{{project.title}}</h5>
                    <p class="card-text">{{project.details}}</p>
                    <div class="progress" style="height:5px;">
                        <div aria-valuemax="{{ project.total_target }}" aria-valuemin="0"
                             aria-valuenow="{{ project.current_fund }}" class="progress-bar progress-bar-striped bg-info progress-bar-animated"
                             role="progressbar" style="width: {{project.percentag}}%;"></div>
                    </div>
                    <div class="d-flex justify-content-between">
                        <p>{{project.current_fund }} / {{ project.total_target}}</p>
                        <p>{{project.percentag}} %</p>
                    </div>
                    <a class="btn text-white  mt-1" href="{% url 'project_details' project.slug %}"
                       style="background-color: #13ADB7;">Show project</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}