crowdfunding/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import home
urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('newproj/', include('newproj.urls')),
    path('homepage/', include('homepage.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('search/',  views.search, name="search"),
    path('api/projects/', views.get_projects_by_category_id, name='get_projects_by_category_id'),

]

newproj/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects_list, name='projects_list'),
    path('create/', views.create_project, name='create_project'),
    path('<slug:slug>/', views.project_details, name='project_details'),
    path('<slug:slug>/rate', views.rate_project, name='rate_project'),
    path('<slug:slug>/donate/', views.add_donation, name='add_donation'),
    path('<slug:slug>/cancel/', views.cancel_project, name='cancel_project'),
    path('<slug:slug>/rate/', views.rate_project, name='rate_project'),
    path('<slug:slug>/donate/', views.add_donation, name='add_donation'),
    path('<slug:slug>/comment/', views.add_comment, name='add_comment'),
    path('<slug:slug>/report/', views.report_project, name='report_project'),
    path('comments/<int:comment_id>/report/', views.report_comment, name='report_comment'),
    path('tags/<slug:slug>/', views.tagged, name="tagged"),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import  forms

class SearchForm(forms.Form):
    options = [('project', 'Project'), ('tag', 'Tag')]
    search_option = forms.ChoiceField(choices=options)
    query = forms.CharField(max_length=100, label='', required=True)

    def clean_query(self):
        query = self.cleaned_data.get("query")
        if not query or query.isspace():
            raise forms.ValidationError("This field cannot be empty.")
        return query

homepage/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Avg, Count
from taggit.models import Tag
from .forms import SearchForm
from django.utils import timezone
from django.http import JsonResponse
from newproj.models import Project, Category
# from apps.models import Category
from accounts.models import CustomUser

# Create your views here.

def home_page(request):
    top_projects = Project.objects.filter(status='active', end_time__gt=timezone.now()).order_by('-rate')[:5]
    categories = Category.objects.all()
    categories_projects=Project.objects.all()
    for project in categories_projects:
        percentage = project.current_fund * 100 / project.total_target
        project.percentage = "{:.3f}".format(percentage)

    latest_projects = Project.objects.filter(status='active').order_by('-start_time')[:5]
    for project in latest_projects:
        percentage = project.current_fund * 100 / project.total_target
        project.percentage = "{:.3f}".format(percentage)

    featured_projects = Project.objects.filter(featured=True,status='active').order_by('-featured_at')[:5]
    for project in featured_projects:
        percentage = project.current_fund * 100 / project.total_target
        project.percentage = "{:.3f}".format(percentage)

    return render(request, 'index.html',context = {'top_projects':top_projects,
                                                            'latest_projects': latest_projects,
                                                            'featured_projects':featured_projects,
                                                            'categories':categories,
                                                            'categories_projects':categories_projects,
                                                            })

def get_projects_by_category_id(request):
    category_id = request.GET.get('category_id')
    if category_id:
        projects = Project.objects.filter(category_id=category_id,status='active')
    else:
        projects = Project.objects.all()

    for project in projects:
        percentage = project.current_fund * 100 / project.total_target
        project.percentage = "{:.3f}".format(percentage)

    data = [{'id': project.id, 'title': project.title, 'details': project.details, 
             'picture_url': project.picture_url, 'current_fund': project.current_fund, 
             'total_target': project.total_target,'slug':project.slug, 'percentage': project.percentage} 
            for project in projects]

    return JsonResponse({'projects': data})
    
def search(request):
    form = SearchForm(request.GET)
    results = []

    if form.is_valid():
        search_option = form.cleaned_data['search_option']
        query = form.cleaned_data['query'].strip()  # Remove leading/trailing spaces

        if search_option == 'project':
            results = Project.objects.filter(title__icontains=query)
            print(results)
        elif search_option == 'tag':
            # Filter projects by tags
            results = Project.objects.filter(tags__name__icontains=query)
            print(results)
        else:
            results = []
    else:
        results = []

    return render(request, 'search_results.html', {'searchForm': form, 'searchResults': results})
 
    

homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <title>{% block title %} {%endblock%}</title>

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet"
    />

    <!-- Font-Awesome -->
    <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          referrerpolicy="no-referrer" rel="stylesheet"
    />
    <style>
        .form-control:focus {
            border-color: rgba(0, 0, 0, 0.15); 
            box-shadow: none; 
        }
    </style>
    {% block styles %}{% endblock %}

</head>
<body>
<!-- Start Navbar -->
{% block navbar %} {% endblock%}
<!-- End Navbar -->

<!-- Start Content -->

<div>{% block content %} {% endblock%}</div>
<!-- End Content -->

<!-- Start Footer -->
<div>{% block footer %} {% endblock%}</div>
<!-- End Footer -->

{%block scripts %}

<script crossorigin="anonymous" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock%}

</body>
</html>

homepage/templates/search_results.html
{% extends 'base.html' %}

{% block content %}

{% block styles %}

<style>

.section{
    margin-top: 100px;
}
</style>
{% endblock %}
<!-- Start hero section -->
<section class="d-flex align-items-center justify-content-center hero-section-header-bg section" id="hero-section">
<div class="container">
    <div class="d-flex align-items-center justify-content-center flex-column g-3 ">
        <div class="rounded-5 border border-danger-subtle px-1 w-50 bg-white">
            <form method="GET" action="{% url 'search' %}" class="d-flex align-items-center position-relative  ">
                <!-- {{form}} -->
                <div class="m-1">
                    {{searchForm.search_option}}
                </div>
                <div class="m-1">
                    {{searchForm.query}}
                </div>
                <button class="btn btn-special rounded-5 px-4 py-2 position-absolute align-items-center m-1 end-0">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <h3 class="mt-4">Search Results</h3>
    </div>
</div>
</section>

<div class="container my-5">
    <div class="row mb-5 g-4">
        {% if searchResults %}
            {% for searchResult in searchResults %}
                <div class="item col-3">
                        <div class="card p-2 bg-light">
                            <img src="{{searchResult.picture_url}}" style=" height: 200px; width: 100%;" class="card-img-top"
                                alt="project">
                            <div class="card-body">
                                <h5 class="card-title">{{searchResult.title}}</h5>
                                <p class="card-text">{{searchResult.details}}</p>
                                <progress class="w-100" value="{{ searchResult.current_fund }}"
                                    max="{{ searchResult.total_target }}"></progress>
                                <div class="d-flex justify-content-between">
                                    <p>{{searchResult.current_fund }} / {{ searchResult.total_target}}</p>
                                    <p>{{searchResult.percentag}} %</p>
                                </div>
                                <a href="{% url 'project_details' searchResult.slug %}" class="btn mt-1 text-white " style="background-color:#3dd0d8">Show project</a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        {% else %}
            <h4 class="text-center ">No data available.</h4>
        {% endif %}
    </div>
</div>

<script>
    selectElem = document.querySelector('#id_search_option');
    selectElem.classList.add("form-select", "rounded-5","border","border-danger-subtle");

    searchInput = document.querySelector('#id_query');
    searchInput.classList.add("form-control", "bg-white","border-0","rounded-4","shadow-none","py-3","w-100");
</script>
{% endblock %}